# Generated by Django 2.0 on 2017-12-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globle_id', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('name_with_owner', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('url', models.URLField(blank=True)),
                ('homepage_url', models.URLField(blank=True)),
                ('primary_language', models.CharField(blank=True, max_length=256)),
                ('start_count', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
