# Generated by Django 2.0 on 2017-12-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular',
            name='globle_id',
            field=models.CharField(max_length=256),
        ),
    ]
