# Generated by Django 2.0 on 2017-12-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular', '0002_auto_20171228_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular',
            name='globle_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
