# Generated by Django 2.0 on 2017-12-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular', '0003_auto_20171228_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular',
            name='homepage_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
