# Generated by Django 2.0 on 2017-12-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular', '0004_auto_20171228_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='popular',
            name='homepage_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='popular',
            name='primary_language',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='popular',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
