# Generated by Django 2.0 on 2017-12-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular', '0006_auto_20171228_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular',
            name='description',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='popular',
            name='primary_language',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
