# Generated by Django 2.0 on 2018-01-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular', '0007_auto_20171228_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popular',
            old_name='start_count',
            new_name='star_count',
        ),
    ]
