language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - mkdir -p /home/travis/build/Windsooon/jobder/log_files/
  - touch /home/travis/build/Windsooon/jobder/log_files/info.log
  - touch /home/travis/build/Windsooon/jobder/log_files/error.log
  - ./runtests.py
