# Generated by Django 2.0 on 2018-01-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('job_des', models.CharField(max_length=600)),
                ('onsite', models.URLField(default='')),
                ('homepage_url', models.URLField(default='', null=True)),
                ('primary_language', models.CharField(default='', max_length=256, null=True)),
                ('star_count', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='contribute',
            field=models.ManyToManyField(to='post.Repo'),
        ),
    ]
