# Generated by Django 2.0.1 on 2018-01-26 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('name_with_owner', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('url', models.URLField(blank=True)),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('primary_language', models.CharField(blank=True, max_length=256)),
                ('star_count', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('job_des', models.CharField(max_length=1024)),
                ('onsite', models.SmallIntegerField(default=0)),
                ('visa', models.SmallIntegerField(default=0)),
                ('salary', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('company_des', models.CharField(max_length=1024)),
                ('location', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True)),
                ('apply', models.CharField(max_length=256)),
                ('pay', models.BooleanField(default=False)),
                ('pay_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.IntegerField()),
                ('repo_name', models.CharField(max_length=256)),
                ('owner_name', models.CharField(max_length=256)),
                ('stargazers_count', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('language', models.CharField(max_length=256)),
                ('url', models.URLField(blank=True)),
                ('html_url', models.URLField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='repo',
            field=models.ManyToManyField(to='post.Repo'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
