# Generated by Django 2.0.1 on 2018-02-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='company_des',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='post',
            name='job_des',
            field=models.CharField(max_length=4096),
        ),
    ]
