# Generated by Django 2.0 on 2018-09-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='github_account',
            field=models.URLField(blank=True, null=True),
        ),
    ]
