# Generated by Django 2.0 on 2018-01-04 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contribute',
            new_name='repo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='homepage_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='primary_language',
        ),
        migrations.RemoveField(
            model_name='post',
            name='star_count',
        ),
        migrations.AddField(
            model_name='post',
            name='apply',
            field=models.CharField(default='abc@example.com', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='company_des',
            field=models.CharField(default='hello, sdfsdfsdf', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='company_name',
            field=models.CharField(default='unicooo', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='salary',
            field=models.CharField(default='$100', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repo',
            name='name',
            field=models.CharField(default='django', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repo',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='onsite',
            field=models.SmallIntegerField(default=0),
        ),
    ]
