# Generated by Django 2.0 on 2018-01-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180104_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='guangzhou', max_length=50),
            preserve_default=False,
        ),
    ]
