# Generated by Django 2.0 on 2018-02-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20180204_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='onsite',
            new_name='type',
        ),
    ]
