# Generated by Django 2.0.1 on 2018-02-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20180205_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='language',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
