# Generated by Django 2.0.1 on 2018-02-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20180205_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='language',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
