# Generated by Django 2.0.1 on 2018-01-07 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pay_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
