# Generated by Django 2.0.1 on 2018-01-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_pay_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globle_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('name_with_owner', models.CharField(max_length=256)),
                ('description', models.CharField(default='', max_length=256, null=True)),
                ('url', models.URLField(default='')),
                ('homepage_url', models.URLField(default='', null=True)),
                ('primary_language', models.CharField(default='', max_length=256, null=True)),
                ('star_count', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='repo',
            name='repo_id',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
