# Generated by Django 2.0.1 on 2018-01-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20180109_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repo',
            name='name',
        ),
        migrations.AddField(
            model_name='repo',
            name='html_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='repo',
            name='owner_name',
            field=models.CharField(default='django', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repo',
            name='repo_name',
            field=models.CharField(default='django', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='popular',
            name='description',
            field=models.CharField(blank=True, default='one', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='popular',
            name='homepage_url',
            field=models.URLField(blank=True, default='https://www.apple.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='popular',
            name='primary_language',
            field=models.CharField(blank=True, default='python', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='popular',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
