# Generated by Django 2.0 on 2018-01-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20180109_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='language',
            field=models.CharField(default='python', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repo',
            name='stargazers_count',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
