# Generated by Django 2.0.1 on 2018-01-11 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20180111_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pay_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 11, 12, 35, 41, 952149, tzinfo=utc)),
        ),
    ]
