# Generated by Django 2.0 on 2018-01-12 02:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20180111_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='company_des',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='post',
            name='job_des',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='post',
            name='pay_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 2, 36, 44, 236394, tzinfo=utc)),
        ),
    ]
