# Generated by Django 2.0 on 2018-01-15 04:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20180112_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pay_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 4, 17, 14, 109534, tzinfo=utc)),
        ),
    ]
