# Generated by Django 2.0 on 2018-01-17 03:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20180115_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visa',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='pay_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 17, 3, 25, 9, 547204, tzinfo=utc)),
        ),
    ]
