# Generated by Django 2.0 on 2018-01-17 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20180117_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pay_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
