# Generated by Django 2.0.1 on 2018-01-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20180117_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular',
            name='homepage_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
