# Generated by Django 2.0.1 on 2018-01-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20180123_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='repo_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
