# Generated by Django 2.0.1 on 2018-01-23 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_popular_repo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popular',
            name='repo_id',
        ),
    ]
