# Generated by Django 2.0.1 on 2018-01-23 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_popular_repo_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Popular',
            new_name='Other',
        ),
    ]
