# Generated by Django 2.0.1 on 2018-01-23 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_auto_20180123_0030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Other',
        ),
    ]
