# Generated by Django 2.0.1 on 2018-01-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_delete_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globle_id', models.CharField(max_length=256, unique=True)),
                ('repo_id', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('name_with_owner', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('url', models.URLField(blank=True)),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('primary_language', models.CharField(blank=True, max_length=256)),
                ('star_count', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
