# Generated by Django 2.0.1 on 2018-01-23 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popular',
            name='globle_id',
        ),
    ]
