# Generated by Django 2.0.1 on 2018-01-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0026_remove_popular_globle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
