# Generated by Django 2.0.1 on 2018-01-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_repo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='repo',
            name='html_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
