# Generated by Django 2.0 on 2018-09-16 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '__first__'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.CharField(blank=True, max_length=256)),
                ('post_id', models.IntegerField(blank=True, null=True)),
                ('sub_id', models.CharField(blank=True, max_length=256)),
                ('stripe_name', models.CharField(blank=True, max_length=256)),
                ('stripe_email', models.EmailField(blank=True, max_length=254)),
                ('stripe_zip', models.CharField(blank=True, max_length=256)),
                ('stripe_last4', models.CharField(blank=True, max_length=48)),
                ('stripe_exp_month', models.SmallIntegerField(blank=True, null=True)),
                ('stripe_exp_year', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FakeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=256)),
                ('avatar_url', models.CharField(blank=True, max_length=256)),
                ('repo', models.ManyToManyField(to='post.Repo')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('blog', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('visiable', models.BooleanField(default=True)),
                ('type', models.SmallIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('repo', models.ManyToManyField(to='post.Repo')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='common.Settings'),
        ),
    ]
