# Generated by Django 2.0 on 2018-09-17 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.CharField(blank=True, max_length=256)),
                ('post_id', models.IntegerField(blank=True, null=True)),
                ('sub_id', models.CharField(blank=True, max_length=256)),
                ('stripe_name', models.CharField(blank=True, max_length=256)),
                ('stripe_email', models.EmailField(blank=True, max_length=254)),
                ('stripe_zip', models.CharField(blank=True, max_length=256)),
                ('stripe_last4', models.CharField(blank=True, max_length=48)),
                ('stripe_exp_month', models.SmallIntegerField(blank=True, null=True)),
                ('stripe_exp_year', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='common.Settings'),
        ),
    ]
