# Generated by Django 2.0 on 2018-09-15 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='stripe_customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='common.Settings'),
        ),
    ]
