# Generated by Django 2.0.1 on 2018-01-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='stripe_id',
            new_name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='settings',
            name='stripe_exp_month',
            field=models.SmallIntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='stripe_exp_year',
            field=models.SmallIntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='stripe_last4',
            field=models.SmallIntegerField(default=3333),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='stripe_zip',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
