# Generated by Django 2.0.1 on 2018-02-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20180131_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='stripe_exp_month',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='stripe_exp_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='stripe_last4',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
