# Generated by Django 2.0 on 2018-02-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20180201_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='onsite',
            new_name='type',
        ),
    ]
