# Generated by Django 2.0 on 2018-01-04 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20171222_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='location',
            new_name='onsite',
        ),
    ]
