# Generated by Django 2.0 on 2018-01-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20180115_0851'),
        ('common', '0004_auto_20180104_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='repo',
            field=models.ManyToManyField(to='post.Repo'),
        ),
    ]
