# Generated by Django 2.0 on 2018-09-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_fakeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='stripe_sub_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
