# Generated by Django 2.0.1 on 2018-01-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_settings_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='stripe_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='settings',
            name='stripe_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
