FIND = 'Find Your Match'
LOGIN = 'Log in with Github'
BROWSE = 'Browse Jobs'
TITLE = 'Jobs Recommendation For You'
POSTED = 'Jobs You Created'
RANDOM = 'Jobs List'
STRIPE_API_KEY = 'sk_test_Mrp9fWK53zgna3gSbGGUy60W'
